### ISSUE TITLE
骗人的

### ISSUE THREAD

**Issue by charsdavy** [PizzaLiu/WWDC_Subtitle#2]
根本下载不来中文字幕。wwdc2016

**Comment by PizzaLiu** [comment]
1. `git clone https://github.com/PizzaLiu/WWDC_Subtitle --depth=1`
2. `cd WWDC_Subtitle`
3. `npm install`
4. `node main.js --lang zho --year 2016`

try it before complain

**Comment by charsdavy** [comment]
不要这么块就close issue。问题还没解决呢。
1.下载下来的字幕不是2016年的，虽然命令中指定了2016.
2.下载下来的字幕还是中文的。
